### ISSUE TITLE
issue:Not working with Storyboard.

### ISSUE THREAD

**Issue by KittenYang** [devxoul/UINavigationItem-Margin#2]
I set rightBarButtonItem with storyboard. then set `self.navigationController.navigationItem.rightMargin = 0;`  in viewController ,but it's useless.What's wrong?pls.

**Comment by devxoul** [comment]
Hi @KittenYang,

Have you tried with `self.navigationItem.rightMargin`?

**Comment by devxoul** [comment]
Ummm... that doesn't work. Well, setting bar button item from interface builder won't call `setRightBarButtonItem:`. It's the main problem. I'll take a look for this.

**Comment by devxoul** [comment]
@KittenYang, thank you for waiting.
I've just made a new release 2.0.1, could you please check with this version?

Thanks!

**Comment by KittenYang** [comment]
@devxoul  Great! I'll try it :+1:

**Comment by devxoul** [comment]
@KittenYang, please let me know if it works or not :smile:
