### ISSUE TITLE
Don't support system?

### ISSUE THREAD

**Issue by snail-z** [devxoul/UINavigationItem-Margin#4]
Don't support system NavigationItem?  Set up the system of NavigationItem, doesn't work。

**Comment by devxoul** [comment]
@snail-z could you please explain me some more detail?

**Comment by snail-z** [comment]
I'm sorry my English is poor, I mean on the system of 'NavigationItem back button' doesn't work.
For example:  self navigationController. NavigationItem. LeftMargin = 30;
It is not work.

**Comment by devxoul** [comment]
@snail-z, that's intended because system back button is not a `leftBarButtonItem`.

**Comment by snail-z** [comment]
I see. Thanks
