### ISSUE TITLE
iOS 11 support

### ISSUE THREAD

**Issue by demosthese** [devxoul/UINavigationItem-Margin#8]
Setting custom margin to 0 does not remove system margin.

**Comment by devxoul** [comment]
Yeah, from iOS 11 negative-width UIBarButtonItem doesn't seem to work. I'm going to dig into this for a solution.

**Comment by devxoul** [comment]
@demosthese, I released [2.1.0](https://github.com/devxoul/UINavigationItem-Margin/releases/tag/2.1.0) and it works for iOS 11. Thanks!
